apiVersion: v1
kind: PersistentVolumes
metadata:
   name: my-pv
spec:
   storageClassName: local
   accessModes:
   - ReadWriteMany
   capacity:
     storage: 2Gi
   hostPath:
      path: "/home/ubuntu/"