apiVersion: app/v1
kind: StatefulSet
metadata:
   name: my-statefulset
   namespace: default
spec:
   replicas: 2
   selector:
     matchLabels:
        app: ip-app-stateless
    template:
       metadata:
          labels:
             app: ip-app-stateless
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 8080
