apiVersion: v1
kind: Service
metadata: 
   name: my-headless
   namespace: default
spec: 
   clusterIP: None
   selector: 
     app: ip-app-stateless
   ports:
   - name: http
     port: 32001
     targetPort: 8080 
