apiVersion: v1
kind: ServiceAccount
metadata:
   name: my-sa

---

apiVersion: v1
kind: secret
metadata:
  name: secret-sa
  annotation:
    kubernetes.io/service-account.name: my-sa  # or "my-sa"
type: kubernetes.io/service-account-token